export const testResponse = {
  date: "2025-06-27",
  time_of_day: "15:03",
  request_time: "2025-06-27T15:03:46+01:00",
  station_name: "Roydon",
  station_code: "RYN",
  departures: {
    all: [
      {
        mode: "train",
        service: "21913000",
        train_uid: "Y10006",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "15:13",
        aimed_arrival_time: "15:13",
        aimed_pass_time: null,
        origin_name: "Cambridge North",
        destination_name: "London Liverpool Street",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10006:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "EARLY",
        expected_arrival_time: "15:12",
        expected_departure_time: "15:12",
        best_arrival_estimate_mins: 8,
        best_departure_estimate_mins: 8,
      },
      {
        mode: "train",
        service: "21913000",
        train_uid: "Y10003",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "15:27",
        aimed_arrival_time: "15:27",
        aimed_pass_time: null,
        origin_name: "London Liverpool Street",
        destination_name: "Cambridge North",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10003:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "ON TIME",
        expected_arrival_time: "15:27",
        expected_departure_time: "15:27",
        best_arrival_estimate_mins: 23,
        best_departure_estimate_mins: 23,
      },
      {
        mode: "train",
        service: "21913000",
        train_uid: "Y10402",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "15:30",
        aimed_arrival_time: "15:30",
        aimed_pass_time: null,
        origin_name: "Bishops Stortford",
        destination_name: "Stratford",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10402:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "ON TIME",
        expected_arrival_time: "15:30",
        expected_departure_time: "15:30",
        best_arrival_estimate_mins: 26,
        best_departure_estimate_mins: 26,
      },
      {
        mode: "train",
        service: "21913000",
        train_uid: "Y10392",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "15:39",
        aimed_arrival_time: "15:39",
        aimed_pass_time: null,
        origin_name: "Stratford",
        destination_name: "Bishops Stortford",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10392:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "EARLY",
        expected_arrival_time: "15:38",
        expected_departure_time: "15:38",
        best_arrival_estimate_mins: 34,
        best_departure_estimate_mins: 34,
      },
      {
        mode: "train",
        service: "21913000",
        train_uid: "Y10009",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "15:57",
        aimed_arrival_time: "15:57",
        aimed_pass_time: null,
        origin_name: "London Liverpool Street",
        destination_name: "Cambridge North",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10009:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "ON TIME",
        expected_arrival_time: "15:57",
        expected_departure_time: "15:57",
        best_arrival_estimate_mins: 53,
        best_departure_estimate_mins: 53,
      },
      {
        mode: "train",
        service: "21913000",
        train_uid: "Y10018",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "16:13",
        aimed_arrival_time: "16:13",
        aimed_pass_time: null,
        origin_name: "Cambridge North",
        destination_name: "London Liverpool Street",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10018:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "ON TIME",
        expected_arrival_time: "16:13",
        expected_departure_time: "16:13",
        best_arrival_estimate_mins: 69,
        best_departure_estimate_mins: 69,
      },
      {
        mode: "train",
        service: "21913000",
        train_uid: "Y10015",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "16:27",
        aimed_arrival_time: "16:27",
        aimed_pass_time: null,
        origin_name: "London Liverpool Street",
        destination_name: "Ely (Cambs)",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10015:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "ON TIME",
        expected_arrival_time: "16:27",
        expected_departure_time: "16:27",
        best_arrival_estimate_mins: 83,
        best_departure_estimate_mins: 83,
      },
      {
        mode: "train",
        service: "21913000",
        train_uid: "Y10409",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "16:30",
        aimed_arrival_time: "16:30",
        aimed_pass_time: null,
        origin_name: "Bishops Stortford",
        destination_name: "Stratford",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10409:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "ON TIME",
        expected_arrival_time: "16:30",
        expected_departure_time: "16:30",
        best_arrival_estimate_mins: 86,
        best_departure_estimate_mins: 86,
      },
      {
        mode: "train",
        service: "21913000",
        train_uid: "Y10400",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "16:39",
        aimed_arrival_time: "16:39",
        aimed_pass_time: null,
        origin_name: "Stratford",
        destination_name: "Bishops Stortford",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10400:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "ON TIME",
        expected_arrival_time: "16:39",
        expected_departure_time: "16:39",
        best_arrival_estimate_mins: 95,
        best_departure_estimate_mins: 95,
      },
      {
        mode: "train",
        service: "21913000",
        train_uid: "Y10412",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "16:58",
        aimed_arrival_time: "16:58",
        aimed_pass_time: null,
        origin_name: "Bishops Stortford",
        destination_name: "Stratford",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10412:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "ON TIME",
        expected_arrival_time: "16:58",
        expected_departure_time: "16:58",
        best_arrival_estimate_mins: 114,
        best_departure_estimate_mins: 114,
      },
      {
        mode: "train",
        service: "25913000",
        train_uid: "Y10021",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "17:13",
        aimed_arrival_time: "17:13",
        aimed_pass_time: null,
        origin_name: "London Liverpool Street",
        destination_name: "Cambridge",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10021:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "ON TIME",
        expected_arrival_time: "17:13",
        expected_departure_time: "17:13",
        best_arrival_estimate_mins: 129,
        best_departure_estimate_mins: 129,
      },
      {
        mode: "train",
        service: "21913000",
        train_uid: "Y10407",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "17:26",
        aimed_arrival_time: "17:26",
        aimed_pass_time: null,
        origin_name: "Stratford",
        destination_name: "Bishops Stortford",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10407:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "ON TIME",
        expected_arrival_time: "17:26",
        expected_departure_time: "17:26",
        best_arrival_estimate_mins: 142,
        best_departure_estimate_mins: 142,
      },
      {
        mode: "train",
        service: "21913000",
        train_uid: "Y10416",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "17:30",
        aimed_arrival_time: "17:30",
        aimed_pass_time: null,
        origin_name: "Bishops Stortford",
        destination_name: "Stratford",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10416:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "ON TIME",
        expected_arrival_time: "17:30",
        expected_departure_time: "17:30",
        best_arrival_estimate_mins: 146,
        best_departure_estimate_mins: 146,
      },
      {
        mode: "train",
        service: "25913000",
        train_uid: "Y10027",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "17:43",
        aimed_arrival_time: "17:43",
        aimed_pass_time: null,
        origin_name: "London Liverpool Street",
        destination_name: "Cambridge",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10027:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "ON TIME",
        expected_arrival_time: "17:43",
        expected_departure_time: "17:43",
        best_arrival_estimate_mins: 159,
        best_departure_estimate_mins: 159,
      },
      {
        mode: "train",
        service: "21913000",
        train_uid: "Y10036",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "17:43",
        aimed_arrival_time: "17:43",
        aimed_pass_time: null,
        origin_name: "Cambridge North",
        destination_name: "London Liverpool Street",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10036:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "ON TIME",
        expected_arrival_time: "17:43",
        expected_departure_time: "17:43",
        best_arrival_estimate_mins: 159,
        best_departure_estimate_mins: 159,
      },
      {
        mode: "train",
        service: "21913000",
        train_uid: "Y10418",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "17:58",
        aimed_arrival_time: "17:58",
        aimed_pass_time: null,
        origin_name: "Bishops Stortford",
        destination_name: "Stratford",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10418:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "ON TIME",
        expected_arrival_time: "17:58",
        expected_departure_time: "17:58",
        best_arrival_estimate_mins: 174,
        best_departure_estimate_mins: 174,
      },
      {
        mode: "train",
        service: "25913000",
        train_uid: "Y10033",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "18:13",
        aimed_arrival_time: "18:13",
        aimed_pass_time: null,
        origin_name: "London Liverpool Street",
        destination_name: "Cambridge",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10033:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "ON TIME",
        expected_arrival_time: "18:13",
        expected_departure_time: "18:13",
        best_arrival_estimate_mins: 189,
        best_departure_estimate_mins: 189,
      },
      {
        mode: "train",
        service: "21913000",
        train_uid: "Y10414",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "18:26",
        aimed_arrival_time: "18:26",
        aimed_pass_time: null,
        origin_name: "Stratford",
        destination_name: "Bishops Stortford",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10414:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "ON TIME",
        expected_arrival_time: "18:26",
        expected_departure_time: "18:26",
        best_arrival_estimate_mins: 202,
        best_departure_estimate_mins: 202,
      },
      {
        mode: "train",
        service: "21913000",
        train_uid: "Y10422",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "18:30",
        aimed_arrival_time: "18:30",
        aimed_pass_time: null,
        origin_name: "Bishops Stortford",
        destination_name: "Stratford",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10422:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "ON TIME",
        expected_arrival_time: "18:30",
        expected_departure_time: "18:30",
        best_arrival_estimate_mins: 206,
        best_departure_estimate_mins: 206,
      },
      {
        mode: "train",
        service: "25913000",
        train_uid: "Y10039",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "18:43",
        aimed_arrival_time: "18:43",
        aimed_pass_time: null,
        origin_name: "London Liverpool Street",
        destination_name: "Cambridge",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10039:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "ON TIME",
        expected_arrival_time: "18:43",
        expected_departure_time: "18:43",
        best_arrival_estimate_mins: 219,
        best_departure_estimate_mins: 219,
      },
      {
        mode: "train",
        service: "21913000",
        train_uid: "Y10048",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "18:43",
        aimed_arrival_time: "18:43",
        aimed_pass_time: null,
        origin_name: "Cambridge",
        destination_name: "London Liverpool Street",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10048:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "ON TIME",
        expected_arrival_time: "18:43",
        expected_departure_time: "18:43",
        best_arrival_estimate_mins: 219,
        best_departure_estimate_mins: 219,
      },
      {
        mode: "train",
        service: "25913000",
        train_uid: "Y10045",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "19:13",
        aimed_arrival_time: "19:13",
        aimed_pass_time: null,
        origin_name: "London Liverpool Street",
        destination_name: "Cambridge",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10045:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "ON TIME",
        expected_arrival_time: "19:13",
        expected_departure_time: "19:13",
        best_arrival_estimate_mins: 249,
        best_departure_estimate_mins: 249,
      },
      {
        mode: "train",
        service: "21913000",
        train_uid: "Y10420",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "19:26",
        aimed_arrival_time: "19:26",
        aimed_pass_time: null,
        origin_name: "Stratford",
        destination_name: "Bishops Stortford",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10420:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "ON TIME",
        expected_arrival_time: "19:26",
        expected_departure_time: "19:26",
        best_arrival_estimate_mins: 262,
        best_departure_estimate_mins: 262,
      },
      {
        mode: "train",
        service: "21913000",
        train_uid: "Y10429",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "19:30",
        aimed_arrival_time: "19:30",
        aimed_pass_time: null,
        origin_name: "Bishops Stortford",
        destination_name: "Stratford",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10429:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "ON TIME",
        expected_arrival_time: "19:30",
        expected_departure_time: "19:30",
        best_arrival_estimate_mins: 266,
        best_departure_estimate_mins: 266,
      },
      {
        mode: "train",
        service: "21913000",
        train_uid: "Y10060",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "19:43",
        aimed_arrival_time: "19:43",
        aimed_pass_time: null,
        origin_name: "Cambridge North",
        destination_name: "London Liverpool Street",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10060:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "ON TIME",
        expected_arrival_time: "19:43",
        expected_departure_time: "19:43",
        best_arrival_estimate_mins: 279,
        best_departure_estimate_mins: 279,
      },
      {
        mode: "train",
        service: "21913000",
        train_uid: "Y10056",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "19:57",
        aimed_arrival_time: "19:57",
        aimed_pass_time: null,
        origin_name: "London Liverpool Street",
        destination_name: "Cambridge North",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10056:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "ON TIME",
        expected_arrival_time: "19:57",
        expected_departure_time: "19:57",
        best_arrival_estimate_mins: 293,
        best_departure_estimate_mins: 293,
      },
      {
        mode: "train",
        service: "21913000",
        train_uid: "Y10424",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "20:09",
        aimed_arrival_time: "20:09",
        aimed_pass_time: null,
        origin_name: "Stratford",
        destination_name: "Bishops Stortford",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10424:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "ON TIME",
        expected_arrival_time: "20:09",
        expected_departure_time: "20:09",
        best_arrival_estimate_mins: 305,
        best_departure_estimate_mins: 305,
      },
      {
        mode: "train",
        service: "21913000",
        train_uid: "Y10436",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "20:30",
        aimed_arrival_time: "20:30",
        aimed_pass_time: null,
        origin_name: "Bishops Stortford",
        destination_name: "Stratford",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10436:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "ON TIME",
        expected_arrival_time: "20:30",
        expected_departure_time: "20:30",
        best_arrival_estimate_mins: 326,
        best_departure_estimate_mins: 326,
      },
      {
        mode: "train",
        service: "21913000",
        train_uid: "Y10427",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "20:39",
        aimed_arrival_time: "20:39",
        aimed_pass_time: null,
        origin_name: "Stratford",
        destination_name: "Bishops Stortford",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10427:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "ON TIME",
        expected_arrival_time: "20:39",
        expected_departure_time: "20:39",
        best_arrival_estimate_mins: 335,
        best_departure_estimate_mins: 335,
      },
      {
        mode: "train",
        service: "21913000",
        train_uid: "Y10070",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "20:57",
        aimed_arrival_time: "20:57",
        aimed_pass_time: null,
        origin_name: "London Liverpool Street",
        destination_name: "Cambridge North",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10070:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "ON TIME",
        expected_arrival_time: "20:57",
        expected_departure_time: "20:57",
        best_arrival_estimate_mins: 353,
        best_departure_estimate_mins: 353,
      },
      {
        mode: "train",
        service: "21913000",
        train_uid: "Y10078",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "21:13",
        aimed_arrival_time: "21:13",
        aimed_pass_time: null,
        origin_name: "Ely (Cambs)",
        destination_name: "London Liverpool Street",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10078:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "ON TIME",
        expected_arrival_time: "21:13",
        expected_departure_time: "21:13",
        best_arrival_estimate_mins: 369,
        best_departure_estimate_mins: 369,
      },
      {
        mode: "train",
        service: "21913000",
        train_uid: "Y10445",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "21:30",
        aimed_arrival_time: "21:30",
        aimed_pass_time: null,
        origin_name: "Bishops Stortford",
        destination_name: "Stratford",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10445:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "ON TIME",
        expected_arrival_time: "21:30",
        expected_departure_time: "21:30",
        best_arrival_estimate_mins: 386,
        best_departure_estimate_mins: 386,
      },
      {
        mode: "train",
        service: "21913000",
        train_uid: "Y10434",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "21:39",
        aimed_arrival_time: "21:39",
        aimed_pass_time: null,
        origin_name: "Stratford",
        destination_name: "Bishops Stortford",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10434:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "ON TIME",
        expected_arrival_time: "21:39",
        expected_departure_time: "21:39",
        best_arrival_estimate_mins: 395,
        best_departure_estimate_mins: 395,
      },
      {
        mode: "train",
        service: "21913000",
        train_uid: "Y10081",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "21:57",
        aimed_arrival_time: "21:57",
        aimed_pass_time: null,
        origin_name: "London Liverpool Street",
        destination_name: "Cambridge North",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10081:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "ON TIME",
        expected_arrival_time: "21:57",
        expected_departure_time: "21:57",
        best_arrival_estimate_mins: 413,
        best_departure_estimate_mins: 413,
      },
      {
        mode: "train",
        service: "21913000",
        train_uid: "Y10090",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "22:13",
        aimed_arrival_time: "22:13",
        aimed_pass_time: null,
        origin_name: "Cambridge North",
        destination_name: "London Liverpool Street",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10090:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "ON TIME",
        expected_arrival_time: "22:13",
        expected_departure_time: "22:13",
        best_arrival_estimate_mins: 429,
        best_departure_estimate_mins: 429,
      },
      {
        mode: "train",
        service: "21913000",
        train_uid: "Y10454",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "22:30",
        aimed_arrival_time: "22:30",
        aimed_pass_time: null,
        origin_name: "Bishops Stortford",
        destination_name: "Stratford",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10454:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "ON TIME",
        expected_arrival_time: "22:30",
        expected_departure_time: "22:30",
        best_arrival_estimate_mins: 446,
        best_departure_estimate_mins: 446,
      },
      {
        mode: "train",
        service: "21913000",
        train_uid: "Y10443",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "22:39",
        aimed_arrival_time: "22:39",
        aimed_pass_time: null,
        origin_name: "Stratford",
        destination_name: "Bishops Stortford",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10443:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "ON TIME",
        expected_arrival_time: "22:39",
        expected_departure_time: "22:39",
        best_arrival_estimate_mins: 455,
        best_departure_estimate_mins: 455,
      },
      {
        mode: "train",
        service: "21913000",
        train_uid: "Y10093",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "22:57",
        aimed_arrival_time: "22:57",
        aimed_pass_time: null,
        origin_name: "London Liverpool Street",
        destination_name: "Cambridge North",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10093:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "ON TIME",
        expected_arrival_time: "22:57",
        expected_departure_time: "22:57",
        best_arrival_estimate_mins: 473,
        best_departure_estimate_mins: 473,
      },
      {
        mode: "train",
        service: "21913000",
        train_uid: "Y10103",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "23:13",
        aimed_arrival_time: "23:13",
        aimed_pass_time: null,
        origin_name: "Cambridge North",
        destination_name: "London Liverpool Street",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10103:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "ON TIME",
        expected_arrival_time: "23:13",
        expected_departure_time: "23:13",
        best_arrival_estimate_mins: 489,
        best_departure_estimate_mins: 489,
      },
      {
        mode: "train",
        service: "21913000",
        train_uid: "Y10450",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "23:34",
        aimed_arrival_time: "23:34",
        aimed_pass_time: null,
        origin_name: "Stratford",
        destination_name: "Bishops Stortford",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10450:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "ON TIME",
        expected_arrival_time: "23:34",
        expected_departure_time: "23:34",
        best_arrival_estimate_mins: 510,
        best_departure_estimate_mins: 510,
      },
      {
        mode: "train",
        service: "21913000",
        train_uid: "Y10108",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "23:43",
        aimed_arrival_time: "23:43",
        aimed_pass_time: null,
        origin_name: "Cambridge North",
        destination_name: "London Liverpool Street",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10108:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "ON TIME",
        expected_arrival_time: "23:43",
        expected_departure_time: "23:43",
        best_arrival_estimate_mins: 519,
        best_departure_estimate_mins: 519,
      },
      {
        mode: "train",
        service: "21913000",
        train_uid: "Y10105",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "23:57",
        aimed_arrival_time: "23:57",
        aimed_pass_time: null,
        origin_name: "London Liverpool Street",
        destination_name: "Cambridge",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10105:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "ON TIME",
        expected_arrival_time: "23:57",
        expected_departure_time: "23:57",
        best_arrival_estimate_mins: 533,
        best_departure_estimate_mins: 533,
      },
      {
        mode: "train",
        service: "21913000",
        train_uid: "Y10111",
        platform: null,
        operator: "LE",
        operator_name: "Greater Anglia",
        aimed_departure_time: "00:27",
        aimed_arrival_time: "00:27",
        aimed_pass_time: null,
        origin_name: "London Liverpool Street",
        destination_name: "Cambridge",
        source: "Network Rail",
        category: "OO",
        service_timetable: {
          id: "https://transportapi.com/v3/uk/train/service_timetables/Y10111:2025-06-27.json?app_id=4bdadfad\u0026app_key=5e4d15a6a502d5658cb3b97dcd27b269\u0026live=true",
        },
        status: "ON TIME",
        expected_arrival_time: "00:27",
        expected_departure_time: "00:27",
        best_arrival_estimate_mins: 563,
        best_departure_estimate_mins: 563,
      },
    ],
  },
};
